---
title: "P8105 Homework 1 (zw2975)"
output: github_document
---

```{r library, include = FALSE}
# load library
library(palmerpenguins)
```

## Problem 1

```{r get data from package}
# load the dataset from package
data("penguins", package = "palmerpenguins")
```
#### short descirption of the penguins dataset:
The `Penguins` dataset has variables `species`, `island`, `bill_length_mm`, `bill_depth_mm`, `body_mass_g`, `sex`, and `year`.
This dataset has `r nrow(penguins)` rows and `r ncol(penguins)` columns.
The mean flipper length of this dataset is `r mean(penguins$flipper_length_mm, na.rm = TRUE)`.

#### Scatter plot for bill length vs. flipper length
```{r load library ggplot2, include = FALSE}
library(ggplot2) #for graphing scatterplot
```

```{r making scatterplot, warning = FALSE}
# saving the plot with a name
bill_flipper <- ggplot(penguins, aes(x = bill_length_mm , y = flipper_length_mm, color = species)) +
  geom_point() + 
  labs(title = "Bill length vs. flipper length for different species", 
       x = "Bill length in mm",
       y = "Flipper length in mm")

print(bill_flipper) #display the scatterplot

ggsave("bill_flipper.png") #saving plot in project
```
## Problem 2
```{r load tydiverse, include = FALSE}
library(tidyverse)
```

```{r create dataframe}
dataframe <- tibble(
  x = rnorm(10), # it has a size 10 with standard normal distribution
  vec_logical = x > 10, # True if x>10, false if x<10
  vec_char = c("Hello", "my", "name", "is", "Zhiyu","Wei", "nice", "to", "meet", "you"), # 10 characters
  vec_factor = c("level 1", "level 2", "level 3","level 1", "level 2", "level 3", "level 1", "level 2", "level 3", "level 3" )) # 3 factor levels assigned to each character
```


```{r take mean}
# try to take mean

```


